library(readr)
library(lubridate)
library(reshape2)
library(raster)
library(maptools)
library(plyr)
library(knitr)
library(scales)
library(rgdal)
library(ggmap)
library(gmodels)
library(DT)
library(ggrepel)
library(feather)
library(readxl)
library(tidyr)
library(DBI)
library(dbplyr)
library(odbc)
library(tidyverse)

lapply(list.files(path = 'code/functions',pattern = "[.]R$", recursive = TRUE), function(x) source(paste0('code/functions',"/",x)))
